baseURL = "https://karaner.github.io"
title = "文章"
author = "燃"
copyright = "© 2026, 燃"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]
[pagination]
  pagerSize = 10

# ------------------------------
theme = "hugo-paper"

[params]
  color = 'linen'
  twitter = 'nanxiaobei'
  github = 'karaner'
  instagram = 'nan.xiaobei'

#avatar = 'nanxiaobei@gmail.com'
avatar = 'wenyanhao2011@163.com'
  name = '燃'
  bio = '好学若饥，谦卑若愚。犯其至难，图其至远。'
# ------------------------------

# needed to  render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
#  [markup.highlight]
#    lineNos = true

[menu]

  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "contact"
    name = "联系"
    url = "/contact/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = true
    simple = true

  [privacy.x]
    disabled = true
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = true
    simple = true

  [privacy.youtube]
    disabled = true
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.x]
    disableInlineCSS = true
